config/routes.rb
Rails.application.routes.draw do
  
  resources :items, controller: "cart_items"
  
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end
  

  root 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product

  # Add product to cart
  def add_product_to_cart(product)
    items << product
  end

  # Calculation of the total value
  def total_price
    cart_items.inject(0) { |sum, cart_item| sum + (cart_item.product.price * cart_item.quantity) }
  end

  # Clear cart
  def clean!
    cart_items.destroy_all
  end

  # Find the product on cart
  def find_cart_item(product)
    cart_items.find_by(product_id: product)
  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])

    # If empty, show 0
    unless cart.present?
      cart = Cart.create 
    end

    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    @cart = current_cart
    @item = @cart.cart_items.find_by(product_id: params[:id])
    if @item.product.quantity >= item_params[:quantity].to_i
      @item.update(item_params)
      flash[:notice] = "Updated!"
    else
      flash[:warning] = "Could not update."
    end

    redirect_to carts_path
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart = current_cart
    @item = @cart.find_cart_item(params[:id])
    @product = @item.product
    @item.destroy
    flash[:warning] = "#{@product.name} removed with success!"
    redirect_to :back
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:cart_item).permit(:product_id, :cart_id, :quantity)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def checkout  
  end

  # Method for empty shopping cart
  def clean
    # Call method clean! on model
    current_cart.clean!
    flash[:warning] = "Shopping cart is empty!"
    redirect_to carts_path 
  end 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # Add product to cart
  def add_to_cart
    @product = Product.find(params[:id])

    if !current_cart.items.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "Successfully added product: #{@product.name}"
    else
      flash[:warning] = "Your cart has this product"
    end
  
    redirect_to :back
  
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :quantity, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/checkout.html.erb
Product checkout!

<br />
<br />

<%= link_to "Back", carts_path %>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
<%= link_to "Empty Shopping cart", clean_carts_path , method: :delete , class: "pull-right", style: "text-decoration: underline;", data: { confirm: "Are you sure?"} %>
    <h2> Shopping Cart </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Products info</th>
          <th>Price for unity</th>
          <th>Option </th>
          <th>Quantity</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.items.each do |product| %>
          <tr>
            <td>
              <%= link_to product_path(product) do %>
                <% if product.image.present? %>
                  <%= image_tag product.image.url(:thumb) %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to product.name, product_path(product) %>
            </td>
            <td>
              <%= product.price %>
            </td>
            <td>
              <% item = current_cart.find_cart_item(product) %>
              <%= form_for item, url: item_path(product) do |f| %>
                <%= f.select :quantity, 1..product.quantity %>
                <%= f.submit "Update", data: { disable_with: "Waiting..." } %>
              <% end %>
            </td>
            <td>
              <%= link_to item_path(product), method: :delete do %>
              <i class="glyphicon glyphicon-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
         <span> Total <%= number_to_currency render_cart_total_price(current_cart) %></span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
      <%= link_to("Checkout", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProductsShoppingCart" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Products Shopping Cart</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Products", products_path  %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li>
                <%= link_to carts_path do %>
                  <span class="glyphicon glyphicon-shopping-cart"> </span> Cart ( <%= render_cart_items_count(current_cart) %> )
                <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <hr />

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product", multipart: true } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :quantity, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quantity) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :image, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-3 col-md-2">
      <%= link_to product_path(product) do %>
        <% if product.image.present? %>
          <%= image_tag product.image.url(:thumb), class: "thumbnail" %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
      <%= product.name %><br />
      R$ <%= product.price %>,00
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
      <dd><%= image_tag @product.image.url(:medium) %></dd>
    </dl>
  </div>
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @product.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
      <dd><%= @product.description %></dd>
      <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
      <dd><%= @product.quantity %></dd>
      <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
      <dd><%= @product.price %></dd>
    </dl>

    <div class="pull-right">
      <% if @product.quantity > 0 %>
      <%= link_to "Add to cart", add_to_cart_product_path(@product), method: :post, :class => "btn btn-primary btn-lg btn-info" %>
      <% else %>
        There aren't products in stock
      <% end %>
    </div>

  </div>
</div>